apiVersion: v1
kind: Service
metadata:
  name: redis-srv
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - name: redis-named-port
          containerPort: 6379
        resources:
          limits:
            cpu: "1"
            memory: "2000Mi"
        livenessProbe:
          tcpSocket:
            port: redis-named-port
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 3
